### ISSUE TITLE
elixir myth no action on larval 5.1.x

### ISSUE THREAD

**Issue by rollscia** [joecohens/laravel-elixir-myth#1]
installed myth (npm install -g myth) on local machine (OS X 10.10.4) which using terminal does his job.
Then -> cd to my larval app and npm install --save-dev gulp-myth
Using it through gulp does nothing, no error no action.
If I use sass with Elixir (instead myth) everything works correctly.
Note that during installation I got this warning:
"npm WARN deprecated find-file@0.1.4: Use the globby package instead"
Thank you in advance

**Comment by joecohens** [comment]
Hey! What version of elixir are you using?

**Comment by rollscia** [comment]
Hi Joe,
I am using the version of elixir that comes with Laravel 5.1.8

Thank you for helping

Raul

**Comment by joecohens** [comment]
No problem! So it's using elixir 3, this plugin actually only works for 2.\* I'll try to upgrade it asap. :)

**Comment by rollscia** [comment]
Great, let me know when available.

Thank you
Raul

**Comment by joecohens** [comment]
Hey @rollscia ! I've just upgraded the package to version 0.1.0, can you confirm it's working please?

**Comment by rollscia** [comment]
Thank you Joe.
I will be back in my office next Monday and I will sure test this version and let you know. 

Raul

**Comment by joecohens** [comment]
Awesome thanks!

**Comment by rollscia** [comment]
Hi Joe, I made a Laravel fresh install (5.1.10) on my OS X (10.10.5) machine, but the elixir myth module still doesn't work.
I get this error when I issue gulp command in terminal:
/Library/WebServer/Documents/sph/node_modules/laravel-elixir-myth/index.js:6
var $ = Elixir.Plugins;
        ^
ReferenceError: Elixir is not defined
    at Object.<anonymous> (/Library/WebServer/Documents/sph/node_modules/laravel-elixir-myth/index.js:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Library/WebServer/Documents/sph/gulpfile.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I noticed that the error (Elixir is not defined)  seems to be at this line:
var $ = Elixir.Plugins;
the line above defines elixir var like this: elixir = require('laravel-elixir');
notice lower case as opposite of uppercase of Elixir.Plugins;

Thank you in advance.

**Comment by joecohens** [comment]
Thanks :) it was a typo, can you try again please?

**Comment by rollscia** [comment]
Nope. Now giving error at line 16 (outputDir not defined).

/Library/WebServer/Documents/sph/node_modules/laravel-elixir-myth/index.js:16
    var paths = prepGulpPaths(src, options.srcDir, outputDir);
                                                   ^
ReferenceError: outputDir is not defined
    at Function.<anonymous> (/Library/WebServer/Documents/sph/node_modules/laravel-elixir-myth/index.js:16:52)
    at Function.<anonymous> (/Library/WebServer/Documents/sph/node_modules/laravel-elixir/index.js:44:18)
    at /Library/WebServer/Documents/sph/gulpfile.js:17:9
    at Elixir (/Library/WebServer/Documents/sph/node_modules/laravel-elixir/index.js:18:5)
    at Object.<anonymous> (/Library/WebServer/Documents/sph/gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Moreover I wonder if is correct that larval-elixir-myth folder is not in larval-elixir folder like other modules like in attached pic shown directory structure.
![schermata 2015-08-26 alle 16 00 58](https://cloud.githubusercontent.com/assets/11031499/9495426/c8aec8d6-4c0b-11e5-9991-30ddccef612b.png)

**Comment by joecohens** [comment]
@rollscia Yeah that's ok, it was a typo again haha sorry. It should be working now!

**Comment by rollscia** [comment]
Now no error but not even any output file :(
No file-> public/css/sp.css

---

Fetching Myth Source Files...
- resources/assets/css/sp.css

Saving To...
- public/css/sp.css

[15:16:18] Finished 'default' after 129 ms
[15:16:18] Finished 'myth' after 134 ms
iMac-di-Raul:sph raul$

**Comment by iantearle** [comment]
Im unsure if this is the same issue, but Laravel 5.2.\* after following instructions and running gulp I just get "undefined is not a function".

```
mix.myth("app.css")
        ^
TypeError: undefined is not a function
    at /Users/iantearle/Sites/day100/gulpfile.js:18:9
    at Elixir (/Users/iantearle/Sites/day100/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/Users/iantearle/Sites/day100/gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/iantearle/.nvm/versions/node/v0.12.7/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by joecohens** [comment]
You need to add this package as an `npm install --save-dev laravel-elixir-myth` and add this to your gulpfile.js

```
var elixir = require("laravel-elixir");

require("laravel-elixir-myth");

elixir(function(mix) {
    mix.myth("app.css");
});
```

**Comment by iantearle** [comment]
That's exactly what I have done.

Running install returns this:

```
$ npm install --save-dev laravel-elixir-myth
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
ansi-styles@1.1.0 node_modules/gulp-phpunit/node_modules/ansi-styles -> node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/chalk/node_modules/ansi-styles
has-ansi@0.1.0 node_modules/gulp-phpunit/node_modules/has-ansi -> node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/chalk/node_modules/has-ansi
strip-ansi@0.3.0 node_modules/gulp-phpunit/node_modules/strip-ansi -> node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/chalk/node_modules/strip-ansi
supports-color@0.2.0 node_modules/gulp-phpunit/node_modules/supports-color -> node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/chalk/node_modules/supports-color
/Users/iantearle/Sites/day100
├─┬ babel-preset-es2015@6.6.0
│ └─┬ babel-plugin-transform-regenerator@6.8.0
│   └─┬ babel-core@6.8.0
│     └─┬ babel-register@6.8.0
│       └─┬ source-map-support@0.2.10
│         └─┬ source-map@0.1.32
│           └── amdefine@1.0.0 
├─┬ gulp-myth@1.1.0
│ ├─┬ myth@1.5.0
│ │ ├─┬ postcss@4.1.16
│ │ │ └─┬ source-map@0.4.4
│ │ │   └── amdefine@1.0.0 
│ │ └─┬ rework@1.0.1
│ │   └─┬ css@2.2.1
│ │     └─┬ source-map@0.1.43
│ │       └── amdefine@1.0.0 
│ └─┬ through2@2.0.1
│   └─┬ readable-stream@2.0.6
│     ├── process-nextick-args@1.0.7 
│     └── util-deprecate@1.0.2 
└─┬ laravel-elixir-myth@0.1.2
  └─┬ laravel-elixir@3.4.3
    ├── UNMET PEER DEPENDENCY babel-runtime@^5.8.25
    ├─┬ browser-sync@2.12.8 
    │ ├─┬ eazy-logger@2.1.3
    │ │ └─┬ lodash.clonedeep@4.3.1
    │ │   └── lodash._baseclone@4.5.7 
    │ └─┬ yargs@4.4.0
    │   └─┬ lodash.assign@4.0.9 
    │     ├── lodash.keys@4.0.7 
    │     └── lodash.rest@4.0.3 
    ├─┬ gulp-sass@2.3.1
    │ └─┬ node-sass@3.7.0
    │   └─┬ node-gyp@3.3.1
    │     ├── fstream@1.0.9 
    │     └─┬ npmlog@2.0.3
    │       └─┬ gauge@1.2.7
    │         ├─┬ lodash.pad@4.4.0 
    │         │ ├── lodash._basetostring@4.12.0 
    │         │ └── lodash.tostring@4.1.3 
    │         ├─┬ lodash.padend@4.5.0 
    │         │ └── lodash._basetostring@4.12.0 
    │         └─┬ lodash.padstart@4.5.0 
    │           └── lodash._basetostring@4.12.0 
    ├── UNMET PEER DEPENDENCY vue-hot-reload-api@^1.2.0
    └── UNMET PEER DEPENDENCY vueify-insert-css@^1.0.0

npm WARN vueify@5.0.4 requires a peer of vueify-insert-css@^1.0.0 but none was installed.
npm WARN vueify@5.0.4 requires a peer of babel-runtime@^5.8.25 but none was installed.
npm WARN vueify@5.0.4 requires a peer of vue-hot-reload-api@^1.2.0 but none was installed.
```

and upon running `$ gulp` I get:

```
gulpfile.js:17
    mix.myth('app.css')
        ^
TypeError: undefined is not a function
    at /Users/iantearle/Sites/day100/gulpfile.js:17:9
    at Elixir (/Users/iantearle/Sites/day100/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/Users/iantearle/Sites/day100/gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/iantearle/.nvm/versions/node/v0.12.7/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by joecohens** [comment]
Thanks @iantearle! I've updated the package to v1.0.0 can you confirm it's working now? 

https://github.com/joecohens/laravel-elixir-myth/pull/2

**Comment by iantearle** [comment]
Super thank you @joecohens all working for me.

**Comment by joecohens** [comment]
Awesome! 😄
